Fengfengblog/urls.py
from django.conf import settings  ##新增
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from page.views import backend
from page.views.front_desk.article import article
from page.views.front_desk.history import history
from page.views.front_desk.index import index
from page.views.front_desk.moods import moods
from page.views.front_desk.news import news
from page.views.front_desk.oauth import oauth
from page.views.front_desk.search import search
from page.views.front_desk.sign import sign
from page.views.front_desk.sites import sites
from page.views.front_desk.about import about
from page.views.front_desk.project import project
from page.views.front_desk.login import login
from page.views.front_desk.logout import logout
from page.views.front_desk.get_random_code import get_random_code

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台
    path('admin_home/', backend.admin_home),  # 后台的看板
    path('', index),  # 首页
    path('news/', news),  # 新闻
    path('about/', about),  # 关于
    path('sites/', sites),  # 网站导航
    path('moods/', moods),  # 心情
    path('history/', history),  # 网站历史
    path('search/', search),  # 搜索
    path('project/', project),  # 项目
    path('login/', login),  # 登录
    path('oauth/', oauth),  # 三方登录之后的回调
    path('login/random_code/', get_random_code),  # 图片验证码
    path('sign/', sign),  # 注册
    path('logout/', logout),  # 注销
    re_path(r'^article/(?P<nid>\d+)/', article),  # 文章详情页
    path('backend/', backend.backend),  # 后台个人中心
    path('backend/add_article/', backend.add_article),  # 后台添加文章
    path('backend/edit_avatar/', backend.edit_avatar),  # 后台修改头像
    path('backend/cover_list/', backend.cover_list),  # 文章封面
    path('backend/avatar_list/', backend.avatar_list),  # 头像列表
    re_path(r'^backend/edit_article/(?P<nid>\d+)/', backend.edit_article),  # 编辑文章
    re_path(r'^api/', include('api.urls')),  # 路由分发  将所有已api开头的请求分发到api这个urls.py中
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # 用户上传文件路由配置

]

api/urls.py
from django.urls import path, re_path

from api.views import admin_data
from api.views import api_email
from api.views import article
from api.views import comment
from api.views import file
from api.views import history
from api.views import login
from api.views import mood
from api.views import news
from api.views import sites
from api.views import user

urlpatterns = [
    path('login/', login.LoginView.as_view()),  # 登录

    path('sign/', login.SignView.as_view()),  # 注册

    path('get_online/', admin_data.get_online),  # 获取在线人数

    path('get_seven_data/', admin_data.get_seven_data),  # 七日数据

    path('article/', article.ArticleView.as_view()),  # 发布文章

    # 注意这里的顺序，这个要在修改文章的前面，不然会被他捕获到
    re_path(r'article/(?P<nid>\d+)/comment/', comment.CommentView.as_view()),  # 发布评论

    re_path(r'article/(?P<nid>\d+)/', article.ArticleView.as_view()),  # 修改文章

    re_path(r'article_pwd/(?P<nid>\d+)/', article.ArticlePwdView.as_view()),  # 查看加密文章

    re_path(r'comment/digg/(?P<nid>\d+)/', comment.CommentDiggView.as_view()),  # 评论点赞

    re_path(r'article/digg/(?P<nid>\d+)/', article.ArticleDiggView.as_view()),  # 文章点赞

    re_path(r'article/cover/(?P<nid>\d+)/', article.EditArticleCoverView.as_view()),  # 文章修改封面

    re_path(r'article/collects/(?P<nid>\d+)/', article.ArticleCollectsView.as_view()),  # 文章收藏

    path('projects/', article.ProjectArticleView.as_view()),  # 发布项目

    re_path(r'projects/(?P<nid>\d+)/', article.ProjectArticleView.as_view()),  # 修改项目

    path('moods/', mood.MoodsView.as_view()),  # 发布心情

    re_path(r'moods/(?P<nid>\d+)/', mood.MoodsView.as_view()),  # 删除心情

    re_path(r'mood_comments/(?P<nid>\d+)/', mood.MoodCommentsView.as_view()),  # 发布心情评论

    path('history/', history.HistoryView.as_view()),  # 发布记录

    re_path(r'history/(?P<nid>\d+)/', history.HistoryView.as_view()),  # 编辑记录

    path('site_tag/', sites.NavTagsView.as_view()),  # 发布网站标签

    re_path(r'site_tag/(?P<nid>\d+)/', sites.NavTagsView.as_view()),  # 编辑网站标签

    path('sites/', sites.NavView.as_view()),  # 获取网站数据列表

    re_path(r'sites/(?P<nid>\d+)/', sites.NavView.as_view()),  # 编辑网站数据

    re_path(r'site_digg/(?P<nid>\d+)/', sites.NavDiggView.as_view()),  # 网站点赞

    re_path(r'site_coll/(?P<nid>\d+)/', sites.NavCollectsView.as_view()),  # 网站收藏

    path('friends_links/', sites.FriendLinks.as_view()),  # 添加友链

    path('edit_password/', user.EditPasswordView.as_view()),  # 修改密码

    path('edit_avatar/', user.EditAvatarView.as_view()),  # 修改头像

    path('upload/avatar/', file.AvatarView.as_view()),  # 上传头像

    path('upload/cover/', file.CoverView.as_view()),  # 上传封面

    re_path(r'upload/avatar/(?P<nid>\d+)/', file.AvatarView.as_view()),  # 删除头像

    re_path(r'upload/cover/(?P<nid>\d+)/', file.CoverView.as_view()),  # 删除封面

    path('paste_upload/', file.PasteUpload.as_view()),  # 粘贴上传

    path('send_email/', api_email.ApiEmail.as_view()),  # 发送邮箱

    path('perfect_information/', user.EditUserInfoView.as_view()),  # 绑定信息

    path('cancel_collection/', user.CancelCollection.as_view()),  # 取消收藏

    path('reset_avatar/', user.ResetAvatarView.as_view()),  # 重置头像  qq  gitee  # TODO：废弃

    path('feedback/', user.FeedBackView.as_view()),  # 意见反馈

    path('news/', news.NewsView.as_view()),  # 新闻

]

page/models.py
# @Auth:fengfeng
# @Time:2021/12/31 19:51

"""
主体表结构
UserInfo
Avatars
...
"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_delete  # 删除文件
from django.dispatch.dispatcher import receiver  # 删除文件
from django.utils.html import format_html


# 用户表
class UserInfo(AbstractUser):
    """
    nick:昵称
    avatar_url:用户头像
    tel:手机号
    integral：用户积分
    token:第三方登录的ID
    ip:IP地址
    addr:用户的地址
    sign_status:注册来源
    account_status:账号的状态
    avatar：头像表
    collects：收藏的文章
    navs:用户收藏的网站
    """
    nid = models.AutoField(primary_key=True)
    nick_name = models.CharField(max_length=16, verbose_name='昵称', null=True, blank=True)
    avatar_url = models.URLField(verbose_name='用户头像', help_text='可能是其他平台的头像', null=True, blank=True)
    tel = models.CharField(verbose_name='手机号', max_length=12, null=True, blank=True)
    integral = models.IntegerField(default=20, verbose_name='用户积分')
    token = models.CharField(verbose_name='id', help_text='其他平台的唯一登录id', max_length=64, null=True, blank=True)
    ip = models.GenericIPAddressField(verbose_name='ip地址', default='120.228.2.238')
    addr = models.TextField(verbose_name='用户地址信息', null=True, blank=True)
    sign_choice = (
        (0, '用户名注册'),
        (1, 'QQ注册'),
        (2, 'gitee注册'),
        (3, '手机号注册'),
        (4, '邮箱注册'),
    )
    sign_status = models.IntegerField(default=0, choices=sign_choice, verbose_name='注册方式')
    account_status_choice = (
        (0, '账号正常'),
        (1, '账号异常'),
        (2, '账号被封禁'),
    )
    account_status = models.IntegerField(default=0, choices=account_status_choice, verbose_name='账号状态')
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='用户头像',
        null=True,
        blank=True,
    )
    collects = models.ManyToManyField(
        to='Articles',
        verbose_name='收藏的文章',
        blank=True
    )
    navs = models.ManyToManyField(
        to='Navs',
        verbose_name='收藏的网站',
        blank=True
    )

    class Meta:
        verbose_name_plural = '用户'


# 用户头像表
class Avatars(models.Model):
    """
    url: 头像的链接，完整url: .url
    """
    nid = models.AutoField(primary_key=True)
    url = models.FileField(verbose_name='用户头像地址', upload_to='avatars/')

    def __str__(self):
        return str(self.url)

    class Meta:
        verbose_name_plural = '用户头像'


# 删除头像
@receiver(pre_delete, sender=Avatars)  # sender=你要删除或修改文件字段所在的类**
def avatar_delete(instance, **kwargs):  # 函数名随意
    # print('进入文件删除方法，删的是', instance.url)  # 用于测试
    instance.url.delete(False)  # file是保存文件或图片的字段名**


# 文章表
class Articles(models.Model):
    """
    title：文章标题
    abstract：文章简介
    content：文章内容
    create_date：创建日期
    change_date：编辑的最新日期
    status：文章的状态，默认都是已发布
    recommend：是否上推荐
    cover：文章封面  一对多
    look_count：浏览量
    comment_count：评论数
    digg_count：点赞数
    collects_count：收藏数
    category：文章分类
    tag：文章标签 多对多
    pwd：文章密码
    author：文章的作者  后续可以做一对多，关联用户表
    source：文章的来源
    link：来源地址
    word：文章字数
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标题', max_length=32, null=True, blank=True)
    abstract = models.CharField(verbose_name='文章简介', max_length=128, null=True, blank=True)
    content = models.TextField(verbose_name='文章内容', null=True, blank=True)
    create_date = models.DateTimeField(verbose_name='文章发布日期', auto_now_add=True, null=True)
    change_date = models.DateTimeField(verbose_name='文章修改日期', auto_now=True, null=True)
    status_choice = (
        (0, '未发布'),
        (1, '已发布'),
    )
    status = models.IntegerField(verbose_name='文章保存状态', choices=status_choice)
    recommend = models.BooleanField(verbose_name='是否上推荐', default=True)
    cover = models.ForeignKey(
        to='Cover',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='文章封面', null=True, blank=True
    )
    look_count = models.IntegerField(verbose_name='文章阅读量', default=0)
    comment_count = models.IntegerField(verbose_name='文章评论量', default=0)
    digg_count = models.IntegerField(verbose_name='文章点赞量', default=0)
    collects_count = models.IntegerField(verbose_name='文章收藏数', default=0)
    category_choice = (
        (1, '前端'),
        (2, '后端'),
        (3, '项目相关'),
    )
    category = models.IntegerField(verbose_name='文章分类', choices=category_choice, null=True, blank=True)
    tag = models.ManyToManyField(
        to='Tags',
        verbose_name='文章标签',
        blank=True
    )
    pwd = models.CharField(max_length=32, verbose_name='文章密码', null=True, blank=True)
    author = models.CharField(max_length=16, verbose_name='作者', null=True, blank=True)
    source = models.CharField(max_length=32, verbose_name='来源', null=True, blank=True)

    link = models.URLField(verbose_name='文章链接', null=True, blank=True)
    word = models.IntegerField(verbose_name='文章字数', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '文章'


# 项目分类
class Project(models.Model):
    """
    title：项目的标题
    article：项目关联的文章  多对多
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标题', max_length=32, null=True, blank=True)
    article = models.ManyToManyField(
        verbose_name='文章',
        to='Articles'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '项目相关'


# 评论表
class Comment(models.Model):
    """
    digg_count：点赞数
    article：关联的文章  一对多
    user：关联的用户  一对多
    content： 评论内容
    comment_count： 子评论数
    drawing：配图
    create_time： 创建时间
    parent_comment： 父评论，根评论的父评论为None
    """
    nid = models.AutoField(primary_key=True)
    digg_count = models.IntegerField(verbose_name='点赞', default=0)
    article = models.ForeignKey(verbose_name='评论文章', to='Articles', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE, null=True)
    content = models.TextField(verbose_name='评论内容')
    comment_count = models.IntegerField(verbose_name='子评论数', default=0)
    drawing = models.TextField(verbose_name='配图', null=True, blank=True)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='是否是父评论')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '评论'


# 文章封面
class Cover(models.Model):
    nid = models.AutoField(primary_key=True)
    url = models.FileField(verbose_name='文章封面地址', upload_to='article_img/')
    dominant_hue = models.CharField(verbose_name='封面主色调', max_length=16, null=True, blank=True)
    is_dark = models.BooleanField(verbose_name='是否是深色系', null=True, blank=True)

    def __str__(self):
        return str(self.url)

    class Meta:
        verbose_name_plural = '文章封面'


# 删除封面
@receiver(pre_delete, sender=Cover)  # sender=你要删除或修改文件字段所在的类**
def cover_delete(instance, **kwargs):  # 函数名随意
    # print('进入文件删除方法，删的是', instance.url)  # 用于测试
    instance.url.delete(False)  # file是保存文件或图片的字段名**


# 标签表
class Tags(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=16, verbose_name='标签名字')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '文章标签'


# 回忆录
class History(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='事件名称')
    content = models.TextField(verbose_name='事件内容')
    create_date = models.DateField(verbose_name='创建时间', null=True)
    drawing = models.TextField(verbose_name='配图组，以;隔开', null=True, blank=True)

    class Meta:
        verbose_name_plural = '回忆录'


# 心情
class Moods(models.Model):
    nid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='发布人', max_length=16)
    ip = models.GenericIPAddressField(verbose_name='ip地址', default='120.228.2.238')
    addr = models.TextField(verbose_name='用户地址信息', null=True)
    create_date = models.DateTimeField(verbose_name='发布时间', auto_now=True)
    content = models.TextField(verbose_name='心情内容')
    drawing = models.TextField(verbose_name='配图组，以;隔开', null=True, blank=True)
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    digg_count = models.IntegerField(verbose_name='点赞数', default=0)
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='心情的发布头像'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '心情'


# 心情评论
class MoodComment(models.Model):
    nid = models.AutoField(primary_key=True)
    avatar = models.ForeignKey(
        to='Avatars',
        to_field='nid',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='心情的发布头像'
    )
    name = models.CharField(verbose_name='评论人', max_length=16, null=True)
    content = models.TextField(verbose_name='评论内容')
    digg_count = models.IntegerField(verbose_name='点赞数', default=0)
    ip = models.GenericIPAddressField(verbose_name='ip地址', default='120.228.2.238')
    addr = models.TextField(verbose_name='用户地址信息', null=True)
    mood = models.ForeignKey(
        to='Moods',
        to_field='nid',
        on_delete=models.SET_NULL,
        verbose_name='评论的心情',
        null=True
    )
    create_date = models.DateTimeField(
        verbose_name='评论时间', auto_now=True
    )

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = '心情评论'


# 网站导航
class Navs(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32, verbose_name='网站标题')
    abstract = models.CharField(max_length=128, verbose_name='网站简介', null=True)
    href = models.URLField(verbose_name='网站链接')
    icon_href = models.URLField(

api/views/history.py
import datetime

from django import forms
from django.http import JsonResponse
from django.views import View

from api.forms import clean_form
from page.models import History
from lib.permissions_control import is_super_method

"""
在实际的体验中，回忆录的功能挺弱的，考虑不把它放入导航中
"""


class HistoryForm(forms.Form):
    title = forms.CharField(error_messages={'required': '请输入事件标题'})
    content = forms.CharField(error_messages={'required': '请输入事件内容'})
    create_date = forms.CharField(required=False)
    drawing = forms.CharField(required=False)

    def clean_create_date(self):
        create_date = self.cleaned_data['create_date']
        if not create_date:
            create_date = datetime.date.today()
            return create_date
        date = datetime.datetime.strptime(create_date.split('T')[0], '%Y-%m-%d').date()
        return date


class HistoryView(View):
    @is_super_method
    def post(self, request, **kwargs):

        res = {
            'msg': '记录发布成功！',
            "code": 412,
            "self": None,
        }
        if not request.user.is_superuser:
            res['msg'] = '用户验证失败'
            return JsonResponse(res)
        data = request.data

        form = HistoryForm(data)
        if not form.is_valid():
            res['self'], res['msg'] = clean_form(form)
            return JsonResponse(res)
        res['code'] = 0
        nid = kwargs.get('nid')
        if nid:
            # 编辑操作
            history_query = History.objects.filter(nid=nid)
            history_query.update(**form.cleaned_data)
            res['msg'] = '记录编辑成功'
            return JsonResponse(res)
        History.objects.create(**form.cleaned_data)
        return JsonResponse(res)

    @is_super_method
    def delete(self, request, nid):
        res = {
            'msg': '记录发布成功！',
            "code": 412,
        }
        if not request.user.is_superuser:
            res['msg'] = '用户验证失败'
            return JsonResponse(res)
        history_query = History.objects.filter(nid=nid)
        history_query.delete()
        res['code'] = 0
        return JsonResponse(res)

templates/about.html
{% extends 'article.html' %}
{% load my_tag %}

{% block banner %}
    {% banner 'about' %}
{% endblock %}

templates/article_lock.html
{% extends 'article.html' %}

{% block css %}
    <style>
        .article {
            margin-top: 20px;
            width: 400px;
        }

        .article > .title {
            text-align: center;
        }

        .article > div {
            margin-bottom: 10px;
        }

        .article > .el-button {
            width: 100%;
        }
    </style>
{% endblock %}
{% block main %}
    <div class="slide_or_actions" ref="slider">
        <div class="slider_bar">
            <div class="title">
                <span>[[ slide_text ]]</span>
                <el-switch
                        v-model="isShowSlider"
                        active-color="#13ce66"
                        inactive-color="#9e9e9e"
                        @change="sliderChange"
                >
                </el-switch>
            </div>
            <div class="body">
                <el-scrollbar id="el_scrollbar">
                    <p :tagName="item.tagName" @click="go_side_bar(item.pos, $event)"
                       v-for="(item, index) in slide_list"
                       :key="index">
                        [[ item.c ]]
                    </p>
                </el-scrollbar>
            </div>
        </div>
    </div>
    <div class="article article_clock">
        <div class="title">
            该内容仅VIP可见，若要查看，请输入密码！
        </div>
        <el-input
                id="article_pwd"
                placeholder="请输入文章密码"
                v-model="article_pwd">
        </el-input>
        <el-button type="primary" @click="article_pwd_show('{{ article_obj.nid }}')">查看</el-button>
    </div>
{% endblock %}

{% block article_js %}
    <script>
        $('.slide_or_actions').css('display', 'none')
        setTimeout(() => {
            $('.slide_or_actions').remove()
        }, 301)
    </script>
{% endblock %}

templates/moods.html
{% extends 'index.html' %}
{% load my_tag my_filter %}
{% block banner %}
    {% banner 'moods' %}
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="/static/viewer/css/viewer.css">
    <link rel="stylesheet" href="/static/my/css/moods.css">
{% endblock %}
{% block search %}
    <div class="search">
        <input type="text" @keydown.enter="search('', '_self')" v-model="search_key" class="search_box"
               placeholder="搜索你想要的内容">
        <button @click="search('', '_self')"><i class="fa fa-search"></i></button>
    </div>
{% endblock %}
{% block main %}
    <div class="main">
        <el-dialog
                title="发布心情"
                :visible.sync="mood_dialogVisible"
                :width='max_dialog_width'>
            <div class="add_mood_content body">
                <div>
                    <label for="mood_add_name">用户名</label>
                    <el-input ref="mood_add__name" id="mood_add_name" v-model="mood_add.name"
                              placeholder="请输入用户名"></el-input>
                </div>
                <div>
                    <label for="">头像</label>
                    <ul class="flex avatar_list">
                        {% for avatar in avatar_list %}
                            <li>
                                <el-radio v-model="mood_add.avatar_id" :label="{{ avatar.nid }}">
                                    <img src="{{ avatar.url.url }}" alt="">
                                </el-radio>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div>
                    <label for="mood_add_content">心情内容</label>
                    <el-input ref="mood_add__content" id="mood_add_content" v-model="mood_add.content" resize="none"
                              type="textarea" :rows="4"
                              placeholder="请输入心情内容"></el-input>
                </div>
                <div>
                    <label for="mood_add_drawing">配图</label>
                    <el-input id="mood_add_drawing" v-model="mood_add.drawing" resize="none" type="textarea" :rows="4"
                              placeholder="请输入配图，多个图片使用；隔开"></el-input>
                </div>
                <div class="show_drawing" v-show="mood_show_drawing">
                    <img v-for="(item, index) in mood_show_drawing" :src="item" :key="index" alt="">
                </div>
            </div>
            <span slot="footer" class="dialog-footer">
                <el-button @click="mood_dialogVisible = false">取 消</el-button>
                <el-button type="primary" @click="mood_add_method">确 定</el-button>
              </span>
        </el-dialog>
        <el-dialog
                title="心情回复"
                :visible.sync="mood_comment_dialogVisible"
                :width="min_dialog_width">
            <div class="add_mood_content add_mood_comment">
                <div>
                    <label for="mood_comment_add_name">用户名</label>
                    <el-input ref="mood_comment_add__name" id="mood_comment_add_name" v-model="mood_add_comment.name"
                              placeholder="请输入用户名"></el-input>
                </div>
                <div>
                    <label for="mood_comment_add_content">心情内容</label>
                    <el-input ref="mood_comment_add__content" id="mood_comment_add_content"
                              v-model="mood_add_comment.content" resize="none"
                              type="textarea" :rows="4"
                              placeholder="请输入心情内容"></el-input>
                </div>

            </div>
            <span slot="footer" class="dialog-footer">
    <el-button @click="mood_comment_dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="mood_comment_add_method">确 定</el-button>
  </span>
        </el-dialog>
        <el-button id="pos" @click="mood_dialogVisible = true" class="add_mood">发布心情</el-button>
        {% for mood in mood_list %}
            <div class="mood flex">
                <div class="left">
                    <el-image src="{{ mood.avatar.url.url }}" scroll-container=".el-scrollbar__wrap" lazy
                              alt=""></el-image>
                </div>
                <div class="right">
                    <h3 class="name">{{ mood.name }}</h3>
                    <p class="content">{{ mood.content }}</p>
                    <div class="drawing">
                        {% generate_drawing mood.drawing %}
                    </div>
                    <div class="info flex">
                    <span class="date">
                        {{ mood.create_date|date_humaniz }}
                        <img class="addr" src="/static/my/img/moods/addr.svg" alt="">
                        <i class="addr_info">{{ mood.addr|get_addr }}</i>

                    </span>
                        <span class="three">
                        <span @click="mood_digg('moods', '{{ mood.nid }}', $event)">点赞（{{ mood.digg_count }}）</span>
                        <span @click="mood_show_comment_list($event)"
                              class="mood_comment_num">评论（{{ mood.comment_count }}）</span>
                            {% if request.user.is_superuser %}
                                <span @click="mood_delete('{{ mood.nid }}', $event)" class="delete">删除</span>
                            {% endif %}
                    </span>
                    </div>
                    <ul class="sub_comment_list">
                        {% for comment in mood.moodcomment_set.all %}
                            <li class="flex">
                                <div class="left">
                                    <el-image scroll-container=".el-scrollbar__wrap" lazy
                                              src="{{ comment.avatar.url.url }}" alt=""></el-image>
                                </div>
                                <div class="right">
                                    <h4 class="name">
                                        {{ comment.name }}
                                    </h4>
                                    <p class="content">{{ comment.content }}</p>
                                    <div class="info flex">
                                        <span class="date">{{ comment.create_date|date_humaniz }}
                                        <i class="addr_info sub_info">（{{ mood.addr|get_addr }}）</i>
                                        </span>
                                        <span class="three">
                                    <span @click="mood_digg('mood_comments', '{{ comment.nid }}', $event)">点赞（{{ comment.digg_count }}）</span>
                                            {% if request.user.is_superuser %}
                                                <span @click="mood_sub_comment_delete('{{ comment.nid }}', '{{ mood.nid }}', $event)"
                                                      class="delete">删除</span>
                                            {% endif %}
                                </span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}


                        <el-button type="primary" @click="mood_comment_dialogVisible_show('{{ mood.nid }}')"
                                   class="rep_mood" plain>
                            回复这条心情
                        </el-button>
                    </ul>

                </div>
            </div>
        {% endfor %}

        <ul class="pager">
            {{ pager.page_html|safe }}
        </ul>


    </div>
{% endblock %}
{% block article_js %}
    <script src="/static/viewer/js/viewer.js"></script>
    <script>
        $('.drawing').viewer();
    </script>
{% endblock %}

templates/news.html
{% extends 'index.html' %}
{% load my_tag %}
{% block banner %}
    {% banner 'news' %}
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="/static/my/css/news.css">
{% endblock %}
{% block main %}
    <div class="main">
        <div class="news_content">
            {% csrf_token %}

            <div class="left">
                <ul>
                    <li :class="item.name === news_active ? 'active' : ''" v-for="item in news_init" :key="item.id"
                        @click="get_new_data(item.id, item.name, item.url, false, 0)"><img
                            :src="item.url" alt="">[[ item.name ]]
                    </li>
                </ul>
            </div>
            <div class="right">
                <div class="title">
                    <img :src="news_active_url" alt="">
                    <h2>[[ news_active ]] · 热搜榜</h2>
                </div>
                <div class="body">
                    <ul>
                        <li v-for="item in news_list" :key="item.index">
                            <span class="index">[[ item.index ]]</span> <a
                                :href="item.link"
                                target="_blank">[[ item.title ]]</a>
                            <span class="num">[[ item.hotValue ]]</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="thank"><a href="https://go.itab.link/">灵感与API来源于itab</a></div>

    </div>
{% endblock %}